### YamlMime:Lifecycle
metadata:
  title: Windows Masaüstü için Microsoft Application Virtualization Hosting 5.1
  description: 'Windows Masaüstü için Microsoft Application Virtualization Hosting 5.1, Sabit Yaşam Döngüsü İlkesi''ni izler.'
  ms.date: 09/10/2020
  keywords: for Windows Desktops
name: Windows Masaüstü için Microsoft Application Virtualization Hosting 5.1
summary: |+
  Windows Masaüstü için Microsoft Application Virtualization Hosting 5.1, [Sabit](/lifecycle/policies/fixed) Yaşam Döngüsü İlkesi'ni izler.

  Bu, şu sürümler için geçerlidir: Windows Masaüstü için

products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
  - version: Original Release
    startDate: 11/01/2015
    endDate: 04/14/2026
content: |

  ## <a name="links"></a>Bağlantılar 
  * [Ürün bilgileri](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)


  ## <a name="editions"></a>Sürümler 
  * Windows Masaüstü Bilgisayarlar için