### YamlMime:Lifecycle
metadata:
  title: Windows Masaüstü için Microsoft Application Virtualization Hosting 4.6
  description: Windows Masaüstü için Microsoft Application Virtualization Hosting 4.6, Sabit Yaşam Döngüsü İlkesi'ni izler.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: 8a32729ae5fbf7f57a14b6a6ec048c7a1f412a52
  ms.sourcegitcommit: af46dd09ccdabd80dcc49d2cd930cefa0b1ab8a6
  ms.translationtype: HT
  ms.contentlocale: tr-TR
  ms.lasthandoff: 09/01/2020
  ms.locfileid: "935470"
name: Windows Masaüstü için Microsoft Application Virtualization Hosting 4.6
summary: >+
  Windows Masaüstü için Microsoft Application Virtualization Hosting 4.6, [Sabit](/lifecycle/policies/fixed) Yaşam Döngüsü İlkesi'ni izler.


  Bu, şu sürümler için geçerlidir: Windows Masaüstü için

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>Bağlantılar \n* [Ürün ve geçiş bilgileri](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Hizmet paketi ilkesi](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> App-V 4.6 istemcisi, App-V 4.5 Sunucusu'nu kullandığından, App-V 4.5 Sunucusu, desteklenen App-V 4.6 istemcisi ile birlikte kullanılırken App-V 4.6'nın yaşam döngüsü tarihlerine göre desteklenmeye devam edecektir.\n\n## <a name=\"editions\"></a>Sürümler \n* Windows Masaüstü Bilgisayarlar için"
