### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 5.1
  description: 'Microsoft Application Virtualization 5.1, Sabit Yaşam Döngüsü İlkesi''ni izler.'
  ms.date: 09/10/2020
  keywords: 'for Remote Desktop Services,for Windows Desktops'
name: Microsoft Application Virtualization 5.1
summary: |+
  Microsoft Application Virtualization 5.1, [Sabit](/lifecycle/policies/fixed) Yaşam Döngüsü İlkesi'ni izler.

  Bu, şu sürümler için geçerlidir: Uzak Masaüstü Hizmetleri, Windows Masaüstü

products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
  - version: Original Release
    startDate: 11/01/2015
    endDate: 04/14/2026
content: |

  ## <a name="links"></a>Bağlantılar 
  * [Ürün bilgileri](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)


  ## <a name="editions"></a>Sürümler 
  * Uzak Masaüstü Hizmetleri için
  * Windows Masaüstü Bilgisayarlar için