### YamlMime:Lifecycle
metadata:
  title: Windows Masaüstü için Microsoft Application Virtualization Hosting 4.6
  description: Windows Masaüstü için Microsoft Application Virtualization Hosting 4.6, Sabit Yaşam Döngüsü İlkesi'ni izler.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: 3d5789104bc3b52d4ccfb836df52ddd2ab576d4e
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: tr-TR
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4153944"
name: Windows Masaüstü için Microsoft Application Virtualization Hosting 4.6
summary: >+
  Windows Masaüstü için Microsoft Application Virtualization Hosting 4.6, [Sabit](/lifecycle/policies/fixed) Yaşam Döngüsü İlkesi'ni izler.


  Bu, şu sürümler için geçerlidir: Windows Masaüstü için

products:
- windows
policyType: fixed
supportDates:
  start: 2010-05-27T00:00:00.000-08:00
  end: 2015-07-14T22:59:59.999-08:00
  extendedEnd: 2020-07-14T22:59:59.999-08:00
releases:
- version: Service Pack 3
  startDate: 2013-12-02T00:00:00.000-08:00
  endDate: 2020-07-14T22:59:59.999-08:00
- version: Service Pack 2
  startDate: 2012-10-01T00:00:00.000-08:00
  endDate: 2015-01-13T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2011-01-26T00:00:00.000-08:00
  endDate: 2013-10-08T22:59:59.999-08:00
- version: Original Release
  startDate: 2010-05-27T00:00:00.000-08:00
  endDate: 2012-04-10T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Bağlantılar \n* [Ürün ve geçiş bilgileri](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Hizmet paketi ilkesi](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> App-V 4.6 istemcisi, App-V 4.5 Sunucusu'nu kullandığından, App-V 4.5 Sunucusu, desteklenen App-V 4.6 istemcisi ile birlikte kullanılırken App-V 4.6'nın yaşam döngüsü tarihlerine göre desteklenmeye devam edecektir.\n\n## <a name=\"editions\"></a>Sürümler \n* Windows Masaüstü Bilgisayarlar için"
