### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security, Sabit Yaşam Döngüsü İlkesi'ni izler.
  ms.date: 08/28/2020
  ms.openlocfilehash: d85aea21441458397839241e74939536051397d4
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: tr-TR
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4113429"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security, [Sabit](/lifecycle/policies/fixed) Yaşam Döngüsü İlkesi'ni izler.


products:
- msc
policyType: fixed
supportDates:
  start: 2007-08-02T00:00:00.000-08:00
  extendedEnd: 2015-07-14T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2007-08-02T00:00:00.000-08:00
  endDate: 2015-07-14T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Bağlantılar \n* [Sistem Merkezi Uç Nokta Koruması](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> Forefront Client Security, 14 Temmuz 2015 itibariyle durduruldu. Kötü amaçlı yazılımlardan koruma ve Casus yazılımlardan koruma tanım güncelleştirmeleri, ürün sürümüne göre destek sonuna ulaşınca kullanılabilirlikten çıkacaktır. Lütfen Sistem Merkezi Uç Nokta Koruması'nı bunun yerine koyma olarak değerlendirin."
