### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center 2012 R2 Yapılandırma Yöneticisi
  description: Microsoft System Center 2012 R2 Yapılandırma Yöneticisi, Sabit Yaşam Döngüsü İlkesi'ni izler.
  ms.date: 03/12/2021
  keywords: 
  ms.openlocfilehash: 9e7bbf1db9f64b796da4e0c31bf66ce1b7dea0367121fbaeb1f2f41e60a20772
  ms.sourcegitcommit: 1c28c95e7a2b743cff45216da63f72ffbad026ed
  ms.translationtype: HT
  ms.contentlocale: tr-TR
  ms.lasthandoff: 08/06/2021
  ms.locfileid: "2523693"
name: Microsoft System Center 2012 R2 Yapılandırma Yöneticisi
summary: >+
  Microsoft System Center 2012 R2 Yapılandırma Yöneticisi, [Sabit](/lifecycle/policies/fixed) Yaşam Döngüsü İlkesi'ni izler.


products:
- msc
policyType: fixed
supportDates:
  start: 01/16/2014
  end: 07/11/2017
  extendedEnd: 07/12/2022
releases:
- version: Service Pack 1
  startDate: 05/12/2015
  endDate: 07/12/2022
- version: Original Release
  startDate: 01/16/2014
  endDate: 07/12/2016
content: "\n## <a name=\"links\"></a>Bağlantılar \n* [Hizmet paketi ilkesi](/lifecycle/policies/fixed#service-packs)\n* [Yapılandırma Yöneticisi için Belgelendirme](/mem/configmgr/core/misc/online-documentation)\n* [Geçiş kılavuzu](https://techcommunity.microsoft.com/t5/configuration-manager-blog/system-center-2012-configuration-manager-is-approaching-end-of/ba-p/1650899)"
