### YamlMime:Lifecycle
metadata:
  title: SoftGrid Uygulama Sanallaştırma
  description: SoftGrid Uygulama Sanallaştırma, Sabit Yaşam Döngüsü İlkesi'ni izler.
  ms.date: 09/10/2020
  keywords: 4.1 for Desktops,4.2 for Desktops,for Terminal Services 4.1
  ms.openlocfilehash: 6b63a556c63bca08045d0335bd9233a0ae07a878
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: tr-TR
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4119867"
name: SoftGrid Uygulama Sanallaştırma
summary: >
  SoftGrid Uygulama Sanallaştırma, [Sabit](/lifecycle/policies/fixed) Yaşam Döngüsü İlkesi'ni izler.


  Bu, aşağıdaki sürümler için geçerlidir: Masaüstü Bilgisayarlar için 4.1, Masaüstü Bilgisayarlar için 4.2, Terminal Hizmetleri için 4.1


  > [!IMPORTANT]

  > Destek sona erdi. Aşağıdaki geçiş kılavuzuna bakın.
products:
- windows
policyType: fixed
supportDates:
  start: 2007-05-25T00:00:00.000-08:00
  end: 2012-07-10T22:59:59.999-08:00
  extendedEnd: 2017-07-11T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2007-05-25T00:00:00.000-08:00
  endDate: 2017-07-11T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Bağlantılar \n* [Geçiş kılavuzu](https://technet.microsoft.com/en-us/windows/bb899442)\n\n\n## <a name=\"editions\"></a>Sürümler \n* Masaüstü Bilgisayarlar için 4.1\n* Masaüstü Bilgisayarlar için 4.2\n* Terminal Hizmetleri için 4.1"
