### YamlMime:Lifecycle
metadata:
  title: SoftGrid Uygulama Sanallaştırma
  description: 'SoftGrid Uygulama Sanallaştırma, Sabit Yaşam Döngüsü İlkesi''ni izler.'
  ms.date: 09/10/2020
  keywords: '4.1 for Desktops,4.2 for Desktops,for Terminal Services 4.1'
name: SoftGrid Uygulama Sanallaştırma
summary: |
  SoftGrid Uygulama Sanallaştırma, [Sabit](/lifecycle/policies/fixed) Yaşam Döngüsü İlkesi'ni izler.

  Bu, aşağıdaki sürümler için geçerlidir: Masaüstü Bilgisayarlar için 4.1, Masaüstü Bilgisayarlar için 4.2, Terminal Hizmetleri için 4.1

  > [!IMPORTANT]
  > Destek sona erdi. Aşağıdaki geçiş kılavuzuna bakın.
products:
  - windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
  - version: Original Release
    startDate: 05/25/2007
    endDate: 07/11/2017
content: |

  ## <a name="links"></a>Bağlantılar 
  * [Geçiş kılavuzu](https://technet.microsoft.com/en-us/windows/bb899442)


  ## <a name="editions"></a>Sürümler 
  * Masaüstü Bilgisayarlar için 4.1
  * Masaüstü Bilgisayarlar için 4.2
  * Terminal Hizmetleri için 4.1