### YamlMime:Lifecycle
metadata:
  title: SoftGrid Uygulama Sanallaştırma
  description: SoftGrid Uygulama Sanallaştırması Sabit Yaşam Döngüsü İlkesini izler.
  ms.date: 07/28/2020
  ms.openlocfilehash: 17b8078138b718a634c2561ac4b1e73f3966ce24
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: tr-TR
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "843898"
name: SoftGrid Uygulama Sanallaştırma
summary: >
  SoftGrid Uygulama [Sanallaştırması Sabit](/lifecycle/policies/fixed) Yaşam Döngüsü İlkesini izler.


  Bu, aşağıdaki sürümler için geçerlidir: Masaüstü bilgisayarlar için 4.1, Masaüstü bilgisayarlar için 4.2, Terminal Hizmetleri 4.1 için


  > [!IMPORTANT]

  > Destek sona erdi. Aşağıdaki geçiş kılavuzuna bakın.
products:
- windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Original Release
  startDate: 05/25/2007
  endDate: 07/11/2017
content: "\n## <a name=\"links\"></a>Bağlantı \n* [Geçiş kılavuzu](https://technet.microsoft.com/en-us/windows/bb899442)\n\n\n## <a name=\"editions\"></a>Sürüm \n* Masaüstü Bilgisayarlar için 4.1\n* Masaüstü Bilgisayarlar için 4.2\n* Terminal Hizmetleri 4.1 için"
